### ISSUE TITLE
Be russian

### ISSUE THREAD

**Issue by tieugene** [SlimRG/QML-Tutorial#1]
"QML Самоучитель" - гуглетранслейта перевод.
"Самоучитель QML"

**Comment by SlimRG** [comment]
Вообще-то я переводил без онлайн переводчиков.
Только по словарям.
Мне кажется "Самоучитель QML" неочень звучит, также как и "Самоучитель Java"
Намного приятнее уху звучит "QML Самоучитель" или "Java Самоучитель"
Это, конечно, дело вкуса, но мне нравится так)
